### ISSUE TITLE
run task jacocoDebugReport error: build error :Illegal character in opaque part at index 11

### ISSUE THREAD

**Issue by zhengoogle** [jaredsburrows/android-gradle-java-app-template#22]
Illegal character in opaque part at index 11: jar:file:G:\FileServer\OpenAndroid\teck\UnitTest\JaCoCofull\android-gradle-master\build\intermediates\apk_for_local_test\debugUnitTest\packageDebugUnitTestForUnitTest\apk-for-local-test.ap_

**Comment by jaredsburrows** [comment]
Any update or more information?

**Comment by zhengoogle** [comment]
> Task :mergeDebugShaders
> Task :compileDebugShaders
> Task :generateDebugAssets
> Task :mergeDebugAssets
> Task :packageDebugUnitTestForUnitTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':packageDebugUnitTestForUnitTest'.
> Illegal character in opaque part at index 11: jar:file:G:\FileServer\OpenAndroid\teck\01UnitTest\JaCoCofull\android-gradle-java-app-template-master\build\intermediates\apk_for_local_test\debugUnitTest\packageDebugUnitTestForUnitTest\apk-for-local-test.ap_

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
21 actionable tasks: 8 executed, 13 up-to-date
12:11:47: Task execution finished 'jacocoDebugReport'.
[run task error.log](https://github.com/jaredsburrows/android-gradle-java-app-template/files/2729139/run.task.error.log)

**Comment by jaredsburrows** [comment]
What Gradle command are you running? `gradlew jacocoDebugReport`?

**Comment by zhengoogle** [comment]
android studio gradle task menu => reporting => jacocoDebugReport
